### ISSUE TITLE
Checklist for 7/10

### ISSUE THREAD

**Issue by divideby0** [Spantree/elasticsearch-talk#25]
- [x] Explain master nodes vs client nodes (CH)
  - [x] Explain allocation awareness
- [x] Drill further into tokenizers & analyzers
- [x] Handling relationships
  - [x] Inner Objects
  - [x] Nested Objects
  - [x] Parent/Child
  - [x] Explain (theoretically) how to handle large text using parent/child
- [x] Explain River plugins
  - [x] With JDBC rivers being deprecated, what is the preferred approach for pulling data from a database?
  - [x] What is the recommended approach for updating an existing JDBC river?
  - [x] What would cause a JDBC river to not index all data retrieved by a SQL query and how can this be diagnosed?
  - [x]    What is the recommended approach for updating an existing index (when adding or removing a column to a river)?
  - [x] What is the recommended approach for refreshing an existing index (when the data source has been updated)?
  - [x]  What is the recommended approach for refreshing targeted data in an existing index (when specific source data has been updated)?
- [ ] Demo Logstash/Kibana
  - [ ] Is it possible to perform pseudo SQL joins in Kibana to display meaningful relationships across multiple types? Not really.
  - [ ] Catalog CEP options
  - [ ] If pulling data from a database and not log files, would there be the need to use this application in the Elasticsearch implementation?
- [ ] Talk about various security models (CH)
  - [x] Refer to Found article
  - [x] Show Kibana sample nginx and apache config
  - [x] Talk about ACLs
  - [x] Talk about proxy apps
  - [x] Talk (speculate) about Elasticsearch's future plans surrounding security
    - Sandboxing scripts?
    - Built-in multi-user authentication?
    - Document level security
- [ ] Talk about logging and monitoring
  - [ ] What logs are available other than what's stored at elasticsearch/logs
- JVM Tuning
  - [ ] Refer to [Erik Rose presentation](http://www.slideshare.net/ErikRose/elasticsearch-the-missing-intr) (slide 101+)
- Scaling
  - [ ] When is hosting multiple ES nodes/instances per server a good idea?
  - [ ] When is virtualizing a good idea?
  - [ ] When should you use local vs shared storage?
  - [ ] Are there any considerations when hosting with the cloud?
  - [ ] Why do we prefer AWS over Azure?
